# Generated by Django 4.2.24 on 2025-09-15 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('endereco', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
            ],
            options={
                'unique_together': {('curso', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativa', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
            ],
            options={
                'unique_together': {('curso', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('capacidade', models.PositiveIntegerField(blank=True, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.escola')),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoReconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ip_endereco', models.GenericIPAddressField()),
                ('porta', models.PositiveIntegerField(default=80)),
                ('modelo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MANUTENCAO', 'Manutenção')], default='OFFLINE', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_instalacao', models.DateTimeField()),
                ('ultima_comunicacao', models.DateTimeField(blank=True, null=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sala')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.escola'),
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sala')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.serie')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turno')),
                ('unidade_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.unidadecurricular')),
            ],
            options={
                'indexes': [models.Index(fields=['sala', 'dia_semana', 'horario_inicio'], name='academico_h_sala_id_a57c75_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('escola', 'codigo')},
        ),
    ]
