# Generated by Django 4.2.24 on 2025-09-15 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoReconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_confianca', models.FloatField(default=0.8)),
                ('max_tentativas_por_minuto', models.PositiveIntegerField(default=10)),
                ('timeout_reconhecimento', models.PositiveIntegerField(default=30)),
                ('salvar_imagens_falha', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosBiometricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_facial', models.TextField()),
                ('qualidade_imagem', models.FloatField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentativaReconhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_capturada', models.ImageField(upload_to='biometria/tentativas/')),
                ('score_confianca', models.FloatField()),
                ('sucesso', models.BooleanField()),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.dispositivoreconhecimento')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sala')),
                ('usuario_identificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='biometria/imagens/')),
                ('tipo', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('ATUALIZACAO', 'Atualização'), ('VERIFICACAO', 'Verificação')], max_length=20)),
                ('qualidade', models.FloatField()),
                ('data_captura', models.DateTimeField(auto_now_add=True)),
                ('dados_biometricos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biometria.dadosbiometricos')),
            ],
        ),
    ]
